[project]
authors = ["Yana Zlatanova <35622632+yanazlatanova@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "emotion-recognition"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
pyarrow = ">=20.0.0,<21"
