[project]
name = "emotion-recognition"
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
server = "jupyter server"
app = "streamlit run app.py"

[dependencies]
jupyter = ">=1.1.1,<2"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.3,<4"
pyarrow = ">=19.0.1,<20"
seaborn = ">=0.13.2,<0.14"
nltk = ">=3.9.1,<4"
pyprojroot = ">=0.3.0,<0.4"
r-irkernel = ">=1.3.2,<2"
r = ">=4.4,<4.5"
r-tidyverse = ">=2.0.0,<3"
r-here = ">=1.0.1,<2"
r-arrow = ">=19.0.1,<20"
r-conflicted = ">=1.2.0,<2"
r-janitor = ">=2.2.1,<3"
transformers = ">=4.52.3,<5"
pytorch = ">=2.6.0,<3"
lightning = ">=2.5.1.post0,<3"
torchinfo = ">=1.8.0,<2"
streamlit = ">=1.45.1,<2"
icecream = ">=2.1.4,<3"
scikit-learn = ">=1.6.1,<2"

[environments]
nbmerge = {features = ["nbmerge"], no-default-feature = true}
gpu = {features = ["gpu"]}
format = {features = ["format"], no-default-feature = true}

[feature.nbmerge.dependencies]
nbdime = ">=4.0.2,<5"

[feature.nbmerge.tasks]
nbmerge-setup = "nbdime config-git --enable"
nbmerge = "nbdime mergetool"

[feature.gpu]
system-requirements = {cuda = "12"}

[feature.gpu.dependencies]
pytorch-gpu = ">=2.6.0,<3"

[feature.gpu.tasks]
server_gpu = "jupyter server"

[feature.format.dependencies]
ruff = "*"

[feature.format.tasks]
format = "ruff format --config ruff.toml"

[pypi-dependencies]
hf-xet = ">=1.1.2, <2"

